// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5zTqFQhYfJeg3dgK1IlL1M110vc7zYwc',
    appId: '1:267244385743:web:2d58d4016565b225cf8eba',
    messagingSenderId: '267244385743',
    projectId: 'iust-bus-tracking',
    authDomain: 'iust-bus-tracking.firebaseapp.com',
    storageBucket: 'iust-bus-tracking.appspot.com',
    measurementId: 'G-QTEFHV40HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF3CgluJY-hMpQk4SazuzVv234LnAgpRo',
    appId: '1:267244385743:android:e56bd676b84f1920cf8eba',
    messagingSenderId: '267244385743',
    projectId: 'iust-bus-tracking',
    storageBucket: 'iust-bus-tracking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDORj-6KwndMgI_6V-BRKQgV4-ZuuSoYUQ',
    appId: '1:267244385743:ios:af56d0d941da245fcf8eba',
    messagingSenderId: '267244385743',
    projectId: 'iust-bus-tracking',
    storageBucket: 'iust-bus-tracking.appspot.com',
    iosClientId: '267244385743-1dhmigj5vklc7sjdeg3jbk58f08ectb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.iustBusTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDORj-6KwndMgI_6V-BRKQgV4-ZuuSoYUQ',
    appId: '1:267244385743:ios:af56d0d941da245fcf8eba',
    messagingSenderId: '267244385743',
    projectId: 'iust-bus-tracking',
    storageBucket: 'iust-bus-tracking.appspot.com',
    iosClientId: '267244385743-1dhmigj5vklc7sjdeg3jbk58f08ectb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.iustBusTracking',
  );
}
